# Generated by Django 4.1.7 on 2023-04-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogmodel_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
